spring:
  config:
    import: "file:.env[.properties]"
  devtools:
    add-properties: false
  docker:
    compose:
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    lazy-initialization: true

logging:
  config: 'classpath:log4j2-prod.xml'

server:
  compression:
    enabled: true
    min-response-size: 1024
  servlet:
    context-path: '/api'

bareo:
  banner:
    mode: "[PRODUCTION mode]"
