spring:
  config:
    import: "optional:file:.dev.env[.properties]"
  datasource:
    url: 'jdbc:postgresql://localhost:5432/bareo_dev'
    username: 'devuser'
    password: 'password'
  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop
      file: docker/compose/compose-dev.yaml
      stop:
        command: down
        timeout: 20s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

logging:
  config: 'classpath:log4j2-dev.xml'

bareo:
  banner:
    mode: "[DEVELOPMENT mode]"
